[theme]
primaryColor = "#00bcd4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f9f9f9"
textColor = "#31333f"
font = "sans serif"

[client]
# 這行可以強制隱藏側邊欄，讓它預設是收起來的
showSidebarNavigation = false